name: Bex
description: Bex App is a social platform for people who suffer from diabetes.
version: 0.1.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flushbar: 1.10.4
  build_context: 2.0.4
  kt_dart: 0.8.0
  get_it: 5.0.1
  freezed_annotation: 0.12.0
  flutter_hooks: ^0.14.1
  flutter_bloc: 6.0.6
  google_fonts: 1.1.0
  dartz: 0.9.2
  google_maps_flutter: 1.0.2
  hive: ^1.4.4+1
  hive_flutter: 0.3.1
  google_maps_webservice: 0.0.18
  auto_size_text: ^2.1.0
  flutter_config: 1.0.7
  firebase_core: ^0.5.0+1
  cloud_firestore: 0.14.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: 0.12.1
  build_runner: 1.10.1
  lint: 1.3.0
  flutter_launcher_icons: 0.8.1
  json_serializable: ^3.5.0
  flutter_native_splash: ^0.1.9
  # flutter pub run change_app_package_name:main com.ferdzz.bex
  change_app_package_name: 0.1.2

dependency_overrides:
  analyzer: 0.39.17    
  build_resolvers: 1.3.10

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/icons/square_launcher.png"
  adaptive_icon_foreground: "assets/icons/circle_launcher.png"
  adaptive_icon_background: "#eeb012"
  android: true
  ios: true

# fluttergen
flutter_gen:
  colors:
    inputs:
      - assets/color/colors.xml

# flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/images/splash_logo.png
  color: "8ec1c8"

flutter:
  uses-material-design: true
  assets:
    - assets/images/LOGO.png
    - assets/images/SPLASH.png
    - assets/images/BEX.png
    - assets/images/BACKGROUND.png
    - assets/images/ABOUT_BACKGROUND.png
    - assets/icons/navbar_location_outline.png
    - assets/icons/navbar_location.png
    - assets/icons/location_yellow.png
    - assets/icons/location_orange.png
    - assets/icons/location_blue.png
    - assets/icons/navbar_help_outline.png
    - assets/icons/navbar_help_greyed.png
    - assets/icons/navbar_help.png
    - assets/icons/navbar_home.png
    - assets/icons/navbar_home_outline.png
